version: '3.7'

services:
    web:
        build:
            context: ./tailorie
            dockerfile: Dockerfile.prod
        expose:
            - 8000
        env_file:
            - ./.env.prod
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
            - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
        env_file:
            - ./.env.prod.db
    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - web

volumes:
    postgres_data:
